### ISSUE TITLE
ISO15118 CertificateUpdate not covered in OPCP?

### ISSUE THREAD

**Issue by Genis-Han** [hubject/opcp#13]
Hello! I'm interested of OPCP.

Where I can found information about `CertificateUpdate` in `ISO15118`?

Accoding to [ccp.v1](https://github.com/hubject/opcp/blob/main/OPCP-1.0.0/reference/ccp.v1.json), There is `CertificateInstallation` EXI Response API but `CertificateUpdate` EXI seems not.

**Comment by steffenrhinow** [comment]
Hi, CertificateUpdate is not adapted from the market. No known market participant is using that. in ISO15118-20 the update is also already removed

**Comment by Genis-Han** [comment]
Thanks for the explains!
