### ISSUE TITLE
Possible issue in business processes description

### ISSUE THREAD

**Issue by simboel** [hubject/opcp#3]
Hi there,
I think I've found a mistake in the document `OPCP-1.0.0/docs/02_PnC_business-processes.md`

https://github.com/hubject/opcp/blob/5a75210953b11227c59d86c166c397eb242199df/OPCP-1.0.0/docs/02_PnC_business-processes.md?plain=1#L51

Suggestion:
```diff
- The Provisioning Certificate with the regarding PCID must be sent by the MO to the PCP beforehand.
+ The MO can retrieve the Provisioning Certificate from the PCP with the supplied PCID. This Provisioning Certificate must've been sent by the OEM to the PCP beforehand.
```
Reason for change: From my understanding I would assume that the MO cannot send the Provisioning Certificate "beforehand". From the API as described in `OPCP-1.0.0/docs/components/02_provisioning-certificate-pool.md` the MO only "reads" data from the PCP and would use `/v1/oem/provCerts/{pcid}` (Get Provisioning Certificate).

~If it is OK with you, I can create Pull Requests instead of issues to make these suggestions easier to implement on your side.~
Nevermind, already created one.

**Comment by steffenrhinow** [comment]
Thanks Simboel, thats completely correct and is a typo in our description.
