### ISSUE TITLE
Schema reference not defined in CCP json

### ISSUE THREAD

**Issue by somrani** [hubject/opcp#7]
Hi,

I think there's an issue on a json file `./OPCP-1.0.0/reference/ccp.v1.json`
The schema reference "#/components/schemas/ContractCertificate" is not defined the json file.

`"put": {
        "summary": "Add Signed Contract Data to CCP",
        "operationId": "addSignedContractData",
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ContractCertificate"
                }
              }
            }
          },`

**Comment by steffenrhinow** [comment]
Thanks - looks like there was an old reference.
I removed that
